name: Update branches

on:
  schedule:
    - cron: '0 7 * * *'
  workflow_dispatch: {}

permissions:
  contents: write

concurrency:
  group: update
  cancel-in-progress: false

env:
  MINIMUM_TRACKING_VERSION: "0.52.1"

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: DeterminateSystems/nix-installer-action@main
      - name: Orchestrate per-version branches
        run: nix run .#update-branches
